name: Update README with Date

on:
  schedule:
    - cron: '8 23 * * *'  # 每天 UTC 时间午夜，即北京时间早上 8 点
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run date script
        run: |
          node date_script.js
          cat TEMP.txt  # 确认 TEMP.txt 的内容输出到日志中

      - name: Update README
        run: |
          DATE_TEXT=$(cat TEMP.txt)
          echo "DATE_TEXT: $DATE_TEXT"

          # 转义日期文本中的斜杠，以便在 sed 命令中安全使用
          ESCAPED_DATE_TEXT=$(echo "$DATE_TEXT" | sed 's/[\/&]/\\&/g')

          # 删除现有的日期行
          sed -i '/文件最后执行时间: .* (每天早上八点执行一次),/d' README.md

          # 在 <!-- Gif --> 注释后面插入新的日期行
          sed -i "/<!-- Gif -->/a 文件最后执行时间: $ESCAPED_DATE_TEXT, (每天早上八点执行一次)," README.md

      - name: Commit and push if changed
        run: |
          git config --global user.email "1109176988@qq.com"
          git config --global user.name "1109176988"
          git diff --quiet || (git add README.md && git commit -m "Updated README with latest date" && git push)
