name: Update README with Date

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜，即北京时间早上8点

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run date script
        run: node date_script.js > TEMP.txt

      - name: Update README
        run: |
          DATE_TEXT=`cat TEMP.txt`
          sed -i "s/Last updated:.*/Last updated: $DATE_TEXT/" README.md

      - name: Commit and push if changed
        run: |
          git config --global user.email "1109176988@qq.com"
          git config --global user.name "1109176988"
          git diff
          git add README.md
          git commit -m "Updated README with latest date" || echo "No changes to commit"
          git push
