name: Update README with Date

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜，即北京时间早上8点
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate date text
        id: generate-date
        run: |
          DATE_TEXT=$(node -e "console.log(new Date().toISOString())")
          echo "$DATE_TEXT" > TEMP.txt
          echo "::set-output name=date::$DATE_TEXT"

      - name: Check if README is empty
        id: check-readme
        run: |
          if [ ! -s README.md ]; then
            echo "README is empty"
            echo "is_empty=true" >> $GITHUB_ENV
          else
            echo "README is not empty"
            echo "is_empty=false" >> $GITHUB_ENV
          fi

      - name: Update README
        run: |
          DATE_TEXT=$(cat TEMP.txt)
          if [ "$is_empty" = "true" ]; then
            # 如果README为空，直接写入日期信息
            echo "Last updated: $DATE_TEXT" > README.md
          else
            # 如果README不为空，替换现有的日期信息
            ESCAPED_DATE_TEXT=$(echo "$DATE_TEXT" | sed 's/[\/&]/\\&/g')
            sed -i "s|Last updated: .*|Last updated: $ESCAPED_DATE_TEXT|" README.md
          fi
        env:
          is_empty: ${{ env.is_empty }}

      - name: Commit and push if changed
        run: |
          git config --global user.email "1109176988@qq.com"
          git config --global user.name "1109176988"
          git diff --quiet || (git add README.md && git commit -m "Updated README with latest date" && git push)
