name: Update README

on:
  schedule:
    - cron: '0 8 * * *'  # 每天早上8点执行

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run date script
        run: node date_script.js

      - name: Check if README is empty
        run: |
          if [ ! -s README.md ]; then
            echo "README is not empty"
          fi

      - name: Read TEMP.txt
        id: read-temp
        run: echo "DATE_TEXT=$(cat TEMP.txt)" >> $GITHUB_ENV

      - name: Configure Git user
        run: git config --global user.email "1109176988@qq.com"

      - name: Update README
        if: success()
        run: |
          DATE_TEXT=${{ env.DATE_TEXT }}
          echo "$DATE_TEXT" >> README.md
          git add README.md
          git commit -m "Update README with latest execution time"
          git push
